<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BedTrack.Core\BedTrack.Core.csproj" />
    <ProjectReference Include="..\BedTrack.Data\BedTrack.Data.csproj" />
    <ProjectReference Include="..\BedTrack.Services\BedTrack.Services.csproj" />
  </ItemGroup>

</Project>
